# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeswitch < Formula
  desc "Kubernetes context and namespace switching with style."
  homepage "https://github.com/ckt114/kubeswitch"
  version "0.2.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ckt114/kubeswitch/releases/download/v0.2.5/kubeswitch_0.2.5_darwin_arm64.tar.gz"
      sha256 "61fb24c35266dc2092c16f7437fce149f562fa3a194e70ad249f6e44245a7ee4"

      def install
        bin.install "kubeswitch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ckt114/kubeswitch/releases/download/v0.2.5/kubeswitch_0.2.5_darwin_amd64.tar.gz"
      sha256 "aab59ae5f3edea24444231d14138e973ca3f8b0e594cd3720f60438ed362ca0b"

      def install
        bin.install "kubeswitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ckt114/kubeswitch/releases/download/v0.2.5/kubeswitch_0.2.5_linux_arm64.tar.gz"
      sha256 "22f1721dabdaf5fd0831ea1758732d798d6a10386aad95317ff5587b4c96f752"

      def install
        bin.install "kubeswitch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ckt114/kubeswitch/releases/download/v0.2.5/kubeswitch_0.2.5_linux_amd64.tar.gz"
      sha256 "2bd9468192c98c0ad0b4d5b3660ffbe5e3b9a3722e5a3482cd877b31c3a5df1a"

      def install
        bin.install "kubeswitch"
      end
    end
  end
end
